## Configuration that contains directory paths

dataset_dir: 'data/data-USA/'
device_id: 0

# Cascade 0: Full convolution for proposals
cascade0_dir: 'cascade0/'
exp_id: '15042700'
phase: 'train'

cascade0_model: 'vgg_iter_200.caffemodel'
mean_file: 'misc/vgg_mean.npy'
models_dir: 'models/'
conv_prototxt: 'vgg_deploy.prototxt'
full_conv_prototxt_prefix: 'vgg_deploy_fullconv_lv'

data-USA_pyra_widths: [1000, 956, 800, 664, 552, 460, 384, 320, 264, 200]

plot_feat: True


