## Configuration that contains directory paths ##

device_id: 1
feat_sum_on: True
cascade: 'cascade2'
dataset_dir: 'data/data-USA/'
gt_dir: '/home/ryan/data/caltech/data-USA/annotations/'
eval_dir: '/home/ryan/data/caltech/data-USA/res/Ours/'

## ConvNet info
non_cropped_input_h: 82
non_cropped_input_w: 41
input_h: 80
input_w: 40
pad_h: 1
pad_w: 0.5

## Cascade 0: Full convolution for proposals
 # Configs for feature pyramids
exp_id: '15043000'
phase: 'train'
cascade0_model: 'cascade0_iter_200.caffemodel'
cascade1_model: 'cascade1_iter_600.caffemodel'
cascade2_model: 'cascade2_iter_200.caffemodel'
mean_file: 'misc/vgg_mean.npy'
models_dir: 'models/'
conv_prototxt: 'vgg_deploy.prototxt'
full_conv_prototxt_prefix: 'vgg_deploy_fullconv_lv'
data-USA_pyra_widths: [1020, 816, 628, 484, 368, 288, 220, 168, 132]
plot_feat: False

 # Configs for bounding boxes
nms_thres: 0.3
bbox_score_thres: 0.8

print_max_score_on: False
print_iter: 10

plot_bbox_on: False

hard_neg_mining_on: True
hard_mining_thres: 0.2

## Feat summation
feat_sum_exp_dir: 'sum/15050402/'
weights: [8, 1, 2]